### ISSUE TITLE
Newbie with problem executing sterra

### ISSUE THREAD

**Issue by numerosos** [novitae/sterraxcyl#12]
Installed Sterra using pip and manually (git clone).

After running ```sterra```, I get this:

Any help will be very appreciated.
```
(base) mypc@192 ~ % sterra
Traceback (most recent call last):
  File "/Users/me/opt/anaconda3/bin/sterra", line 33, in <module>
    sys.exit(load_entry_point('sterra==2.2.1', 'console_scripts', 'sterra')())
  File "/Users/me/opt/anaconda3/bin/sterra", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/me/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/me/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/me/opt/anaconda3/lib/python3.8/site-packages/sterra-2.2.1-py3.8.egg/sterra/core.py", line 10, in <module>
    from sterra.filerra import *
  File "/Users/me/opt/anaconda3/lib/python3.8/site-packages/sterra-2.2.1-py3.8.egg/sterra/filerra.py", line 7, in <module>
    from sterra.exterra import exman
  File "/Users/me/opt/anaconda3/lib/python3.8/site-packages/sterra-2.2.1-py3.8.egg/sterra/exterra.py", line 1, in <module>
    from sterra.histerra import file_id, add_part, add, get_part, match
  File "/Users/me/opt/anaconda3/lib/python3.8/site-packages/sterra-2.2.1-py3.8.egg/sterra/histerra.py", line 79, in <module>
    def get_part(part_option:str=True) -> tuple[str,str]:
TypeError: 'type' object is not subscriptable
```

**Comment by novitae** [comment]
This error is from the program itself. It comes from the output precision of function (e.g.: `def Function() -> list[dict,str]`). It is optional in the code, and some python configuration on idk might not support it.

I removed it from the code. Uninstall then reinstall (with pip or setup.py), it should work. If it does, close the issue.

Thanks for your contribution !
