### ISSUE TITLE
Got error for export

### ISSUE THREAD

**Issue by mdhz** [novitae/sterraxcyl#13]
Hi,

I am getting the following error when I used the basic usage command:
sterra export -ssid **mysessid** -u **tgtuser** -t **following**

The error I'm getting:

```
|§| Path /home/ubuntu/.local/lib/python3.8/site-packages/sterra/export/ created.
|§| Path /home/ubuntu/.local/lib/python3.8/site-packages/sterra/parts/ created.
|§| Path /home/ubuntu/.local/lib/python3.8/site-packages/sterra/_history_.json created.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/sterra", line 5, in <module>
    from sterra.core import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sterra/core.py", line 10, in <module>
    from sterra.filerra import *
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sterra/filerra.py", line 9, in <module>
    class exporter:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sterra/filerra.py", line 10, in exporter
    def __init__(self, _:object, List:list[dict], file_path:str, Format:str, **kwargs:dict) -> None:
TypeError: 'type' object is not subscriptable
```

**Comment by novitae** [comment]
This error comes from your python version that doesn't support `list[dict]` indication. Im going to fix that rn.

**Comment by novitae** [comment]
The error is fixed, upgrade sterra and all should work ! Reopen if it doesn't.
