### ISSUE TITLE
Error when exporting to csv

### ISSUE THREAD

**Issue by MiniMinnoww** [novitae/sterraxcyl#24]
When exporting to a csv file using this command:
`sterra export -ssid {SSID} -u {Username} -t followers -f csv`

I get an error saying 
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 397-398: character maps to <undefined>`

**Comment by novitae** [comment]
Could you send the full traceback please ? I think it is probably a dumb encoding not specified error as described [here](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters), but I want to be sure

**Comment by MiniMinnoww** [comment]
> Could you send the full traceback please ? I think it is probably a dumb encoding not specified error as described [here](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters), but I want to be sure

`Traceback (most recent call last):
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\Scripts\sterra.exe\__main__.py", line 7, in <module>
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\site-packages\sterra\core.py", line 432, in main
    ret = globals()[module.upper()](**kwargs)
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\site-packages\sterra\core.py", line 89, in EXPORT
    scrape(t,l)
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\site-packages\sterra\core.py", line 59, in scrape
    exporter(_=_, List=__a1List, file_path=file_path, Format=Format, **{"username":username,"target":targlist})()
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\site-packages\sterra\filerra.py", line 20, in __call__
    getattr(self,self.Format.upper())()
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\site-packages\sterra\filerra.py", line 57, in CSV
    w.write(','.join(self.dict_keys)+'\n'+"\n".join([",".join([str(v).replace('\n','</b>').replace(',','</c>') for v in d.values()]) for d in self.list]))
  File "C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 397-398: character maps to <undefined>`

**Comment by novitae** [comment]
I'm currently working on the v3 so I won't push correction for now, what you can do is
- At `C:\Users\fishy\AppData\Local\Programs\Python\Python39\lib\site-packages\sterra\filerra.py, line 57` replace this
```python
w.write(','.join(self.dict_keys)+'\n'+"\n".join([",".join([str(v).replace('\n','</b>').replace(',','</c>') for v in d.values()]) for d in self.list]))
```
- By that:
```python
w.write(','.join(self.dict_keys)+'\n'+"\n".join([",".join([str(v).replace('\n','</b>').replace(',','</c>') for v in d.values()]) for d in self.list]), encoding="utf-8")
```

Tell me if it works or not
