### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by suekenway** [novitae/sterraxcyl#34]
It gives me this error :

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/sterra", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sterra/core.py", line 432, in main
    ret = globals()[module.upper()](**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sterra/core.py", line 77, in EXPORT
    scraper = _instagram(_, original_target, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sterra/stegram.py", line 119, in __init__
    self._checkvalidSessid({"sessionid":sessionid})
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sterra/stegram.py", line 192, in _checkvalidSessid
    r = _check_request_passed(
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/sterra/stegram.py", line 24, in _check_request_passed
    req = requests.get(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by albotroz** [comment]
forget it. Doesn't work anyway...like most osint-tools nowadays

**Comment by novitae** [comment]
> forget it. Doesn't work anyway...like most osint-tools nowadays

open source doesn't pay the bills big boy
