### ISSUE TITLE
Rate limit that doesn't get fixed by waiting

### ISSUE THREAD

**Issue by EstebanOD** [novitae/sterraxcyl#37]
C:\Users\REDACTED\Desktop\HDD\REDACTED\sterra>sterra export -ssid REDACTED -u REDACTED -t followers
           __
      2.2 / /_ ___ ________ __ _
     (_-</ __// -_) __/ __/ _ `/
    /___)⎜__/ \__/_/ /_/  \_,_/
    https://github.com/novitae
    ⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺ ⎺⎺⎺⎺⎺⎺ ⎺⎺ ⎺
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python311\Scripts\sterra.exe\__main__.py", line 7, in <module>
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python311\Lib\site-packages\sterra\core.py", line 432, in main
    ret = globals()[module.upper()](**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python311\Lib\site-packages\sterra\core.py", line 77, in EXPORT
    scraper = _instagram(_, original_target, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python311\Lib\site-packages\sterra\stegram.py", line 136, in __init__
    raise RateLimitError("__a1 line 123 is None")
sterra.SterraException.RateLimitError: Rate limit at __a1 line 123 is None blocks the program. Wait a bit, or change of login account.

**Comment by evan1liu** [comment]
I have the same issue, it seems like Instagram doesn't want programmers to be scrapping their website to look for common followers or common followings

**Comment by Tenshi06** [comment]
I had the same issue too
